version: "3"

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: user
      POSTGRES_DB: buffalo
    volumes:
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql

  frontend:
    container_name: frontend
    build: ./frontend
    depends_on:
      - backend

  backend:
    container_name: backend
    build: ./backend
    env_file: backend.env
    environment:
      PGHOST: postgres
      PGUSER: user
      PGDATABASE: buffalo
      PGPASSWORD: 123456
      DATABASE_URL: "postgresql://user:123456@postgres:5432/buffalo?schema=public"
    depends_on:
      - postgres

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 443:443
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./cert.pem:/etc/nginx/cert.pem
      - ./key.pem:/etc/nginx/key.pem
    depends_on:
      - backend
      - frontend
